"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

type UserRole = "Paciente" | "Médico" | "Secretaria";
type UserAccount = { id: string; name: string; email: string; role: UserRole; status: "Ativo" | "Convite pendente" };

const initialUsers: UserAccount[] = [
  { id: "u1", name: "Dr. Flavio Mizoguchi", email: "flavio@cracare.com.br", role: "Médico", status: "Ativo" },
  { id: "u2", name: "Maria Fernanda Lima", email: "maria.fernanda@exemplo.com", role: "Paciente", status: "Ativo" },
];

export default function SecretariaSettingsPage() {
  const [users, setUsers] = useState(initialUsers);
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [role, setRole] = useState<UserRole>("Médico"); const [message, setMessage] = useState("");
  function createUser(event: FormEvent) { event.preventDefault(); if (!name.trim() || !email.trim()) { setMessage("Informe nome e e-mail para criar o acesso."); return; } setUsers((current) => [{ id: crypto.randomUUID(), name: name.trim(), email: email.trim(), role, status: "Convite pendente" }, ...current]); setMessage(`Acesso de ${name.trim()} criado. O convite para definir a senha está pronto para envio.`); setName(""); setEmail(""); }
  function resetPassword(user: UserAccount) { setMessage(`Link de recuperação de senha preparado para ${user.email}. Na versão com Supabase, ele será enviado por e-mail automaticamente.`); }
  return <main className="min-h-screen bg-[#f8f5f2] p-4 text-[#34292d] sm:p-7"><div className="mx-auto max-w-5xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#a3113a]">Secretaria</p><h1 className="mt-2 text-3xl font-bold">Configurações e acessos</h1><p className="mt-2 text-sm text-[#817578]">Crie acessos e ajude usuários a recuperar a senha.</p></div><Link href="/secretaria" className="rounded-xl border border-[#e6dbd6] bg-white px-4 py-3 text-sm font-semibold text-[#a3113a]">← Voltar</Link></header>{message && <div className="mt-5 rounded-2xl bg-[#edf8f3] px-4 py-3 text-sm font-semibold text-[#187157]">{message}</div>}<section className="mt-7 grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><form onSubmit={createUser} className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Novo usuário</h2><p className="mt-1 text-sm text-[#817578]">Para novo médico, secretaria ou paciente.</p><label className="mt-5 block text-sm font-medium">Nome completo<input value={name} onChange={(event) => setName(event.target.value)} className="mt-2 h-12 w-full rounded-xl border border-[#e9dfda] px-4" /></label><label className="mt-4 block text-sm font-medium">E-mail<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-2 h-12 w-full rounded-xl border border-[#e9dfda] px-4" /></label><label className="mt-4 block text-sm font-medium">Perfil<select value={role} onChange={(event) => setRole(event.target.value as UserRole)} className="mt-2 h-12 w-full rounded-xl border border-[#e9dfda] bg-white px-4"><option>Médico</option><option>Secretaria</option><option>Paciente</option></select></label><button className="mt-5 w-full rounded-xl bg-[#a3113a] px-4 py-3 text-sm font-semibold text-white">Criar acesso</button></form><section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Usuários e recuperação de senha</h2><div className="mt-5 space-y-3">{users.map((user) => <article key={user.id} className="flex flex-col gap-3 rounded-2xl bg-[#fbf7f5] p-4 sm:flex-row sm:items-center sm:justify-between"><div><strong className="text-sm">{user.name}</strong><p className="mt-1 text-xs text-[#817578]">{user.email} · {user.role} · {user.status}</p></div><button type="button" onClick={() => resetPassword(user)} className="self-start rounded-xl border border-[#e6dbd6] bg-white px-4 py-2.5 text-xs font-bold text-[#a3113a]">Recuperar senha</button></article>)}</div></section></section><p className="mt-6 rounded-2xl bg-[#fff7ea] p-4 text-xs leading-6 text-[#806238]">Protótipo: os convites e links ainda são demonstrativos. No acesso real, o Supabase enviará e validará as redefinições de senha com segurança.</p></div></main>;
}
