"use client";
import Image from "next/image";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { createNursingPatient, createNursingReport, loadNursingWorkspace, type NursingDoctor, type NursingPatient, type NursingProfile } from "../../lib/supabase/nursing-records";

type Section = "pacientes" | "laudos";
type ReportType = "prick_test" | "patch_test";
type Report = { id:string; patient_id:string; report_type:ReportType; content:Record<string,unknown>; created_at:string };
const prick=["Controle negativo","Histamina","Dermatophagoides pteronyssinus","Dermatophagoides farinae","Blomia tropicalis","Alternaria","Aspergillus","Cladosporium","Pólen de gramíneas","Pólen de árvores","Gato","Cão","Barata","Leite","Ovo","Amendoim"];
const patch=["Níquel","Sulfato de cobalto","Dicromato de potássio","Mistura de fragrâncias","Bálsamo do Peru","Parafenilenodiamina","Lanolina","Formaldeído","Parabenos","Propilenoglicol","Neomicina","Benzocaína"];
const patchResponsibles=["Patricia Martinski","Alessandra Bitencourt"];

export default function EnfermagemPage(){
 const [section,setSection]=useState<Section>("pacientes"),[profile,setProfile]=useState<NursingProfile|null>(null),[patients,setPatients]=useState<NursingPatient[]>([]),[doctors,setDoctors]=useState<NursingDoctor[]>([]),[reports,setReports]=useState<Report[]>([]),[form,setForm]=useState<"patient"|"report"|null>(null),[selected,setSelected]=useState(""),[type,setType]=useState<ReportType>("prick_test"),[patchResponsible,setPatchResponsible]=useState(patchResponsibles[0]),[results,setResults]=useState<Record<string,string>>({}),[notes,setNotes]=useState(""),[name,setName]=useState(""),[cpf,setCpf]=useState(""),[birthDate,setBirthDate]=useState(""),[phone,setPhone]=useState(""),[doctorId,setDoctorId]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function reload(){const data=await loadNursingWorkspace();setProfile(data.profile);setPatients(data.patients);setDoctors(data.doctors);setReports(data.reports as Report[]);setDoctorId(x=>x||data.doctors[0]?.id||"");}
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void reload().catch(()=>setError("Não foi possível carregar a área de enfermagem."));},[]);
 const patient=patients.find(x=>x.id===selected);const history=useMemo(()=>reports.filter(x=>x.patient_id===selected),[reports,selected]);const substances=type==="prick_test"?prick:patch;
 async function savePatient(e:FormEvent){e.preventDefault();if(!profile||!doctorId)return;try{const id=await createNursingPatient(profile,{name,cpf,birthDate,phone,doctorId});await reload();setSelected(id);setForm(null);setName("");setCpf("");setBirthDate("");setPhone("");setMessage("Paciente cadastrada. Crie agora o laudo.");setSection("laudos");}catch{setError("Não foi possível cadastrar. Revise CPF e os campos obrigatórios.");}}
 async function saveReport(){if(!profile||!patient)return;try{await createNursingReport(profile,{patientId:patient.id,doctorId:patient.doctorId,reportType:type,content:{results,notes,model:type,registeredAt:new Date().toISOString(),nurseName:profile.fullName,examResponsible:type==="prick_test"?"Dr. Sergio Fabricio Maniglia":patchResponsible}});await reload();setForm(null);setResults({});setNotes("");setMessage("Laudo salvo e disponível ao médico responsável.");}catch{setError("Não foi possível salvar o laudo.");}}
 const openReport=(id="")=>{setSelected(id);setType("prick_test");setResults({});setNotes("");setForm("report");setSection("laudos");};
 return <main className="min-h-screen bg-[#f8f5f2] text-[#34292d]"><div className="min-h-screen lg:grid lg:grid-cols-[285px_minmax(0,1fr)]"><aside className="bg-gradient-to-b from-[#b31340] to-[#790b2a] px-7 py-8 text-white"><div className="border-b border-white/15 pb-8"><Image src="/logo-cra-branca.png" alt="CRA Care" width={170} height={115} className="h-auto w-36" priority/><p className="mt-4 text-sm text-white/70">Painel de Enfermagem</p></div><nav className="mt-8 space-y-2"><button onClick={()=>setSection("pacientes")} className={`w-full rounded-2xl px-4 py-3 text-left text-sm ${section==="pacientes"?"bg-white/15 font-semibold":"text-white/80"}`}>Pacientes</button><button onClick={()=>setSection("laudos")} className={`w-full rounded-2xl px-4 py-3 text-left text-sm ${section==="laudos"?"bg-white/15 font-semibold":"text-white/80"}`}>Laudos</button><Link href="/" className="block rounded-2xl px-4 py-3 text-sm text-white/80">Sair</Link></nav></aside><section className="p-6 lg:p-10"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#a3113a]">Área clínica</p><h1 className="mt-2 text-3xl font-bold">{section==="pacientes"?"Pacientes":"Laudos"}</h1><p className="mt-2 text-sm text-[#817578]">{profile?.fullName??"Carregando..."}</p></div><button onClick={()=>section==="pacientes"?setForm("patient"):openReport()} className="rounded-xl bg-[#a3113a] px-5 py-3 font-bold text-white">{section==="pacientes"?"+ Cadastrar paciente":"+ Novo laudo"}</button></header>{(message||error)&&<p className={`mt-5 rounded-xl p-4 text-sm ${error?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{error||message}</p>}
 {section==="pacientes"?<section className="mt-8 rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Pacientes cadastradas</h2><p className="mt-1 text-sm text-[#817578]">Acesso apenas aos dados e histórico de laudos.</p><div className="mt-6 space-y-3">{patients.length===0?<p className="rounded-xl border border-dashed p-7 text-center text-sm text-[#817578]">Nenhuma paciente cadastrada.</p>:patients.map(p=><article key={p.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border p-5"><div><strong>{p.name}</strong><p className="mt-1 text-sm text-[#817578]">CPF {p.cpf} · Médico: {p.doctorName}</p><p className="mt-2 text-xs font-bold text-[#a3113a]">{reports.filter(r=>r.patient_id===p.id).length} laudo(s)</p></div><button onClick={()=>{setSelected(p.id);setSection("laudos");}} className="rounded-xl border px-4 py-3 text-sm font-bold text-[#a3113a]">Visualizar histórico</button></article>)}</div></section>:<section className="mt-8 rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Laudos</h2><p className="mt-1 text-sm text-[#817578]">Laudo Prick ou Patch e histórico por paciente.</p></div><select value={selected} onChange={e=>setSelected(e.target.value)} className="rounded-xl border p-3"><option value="">Selecione a paciente</option>{patients.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>{patient&&<><div className="mt-6 flex items-center justify-between rounded-2xl bg-[#fbf5f2] p-4"><div><strong>{patient.name}</strong><p className="text-xs text-[#817578]">Médico: {patient.doctorName}</p></div><button onClick={()=>openReport(patient.id)} className="rounded-xl bg-[#a3113a] px-4 py-2 text-sm font-bold text-white">+ Novo laudo</button></div><div className="mt-5 space-y-3">{history.length===0?<p className="rounded-xl border border-dashed p-5 text-sm text-[#817578]">Nenhum laudo salvo.</p>:history.map(r=><article key={r.id} className="rounded-2xl border p-5"><div className="flex justify-between"><strong>{r.report_type==="prick_test"?"Laudo Prick":"Laudo Patch"}</strong><span className="text-xs text-[#817578]">{new Date(r.created_at).toLocaleDateString("pt-BR")}</span></div><p className="mt-2 text-sm">Responsável: {String(r.content.examResponsible??"Não informado")}</p><p className="text-sm">Enfermeira: {String(r.content.nurseName??"Não informado")}</p></article>)}</div></>}</section>}
 {form==="patient"&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4"><form onSubmit={savePatient} className="w-full max-w-xl rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">Cadastrar paciente</h2><button type="button" onClick={()=>setForm(null)}>×</button></div><div className="mt-5 grid gap-3"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Nome completo" className="rounded-xl border p-3"/><input required value={cpf} onChange={e=>setCpf(e.target.value)} placeholder="CPF" className="rounded-xl border p-3"/><input required type="date" value={birthDate} onChange={e=>setBirthDate(e.target.value)} className="rounded-xl border p-3"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Telefone / WhatsApp" className="rounded-xl border p-3"/><select required value={doctorId} onChange={e=>setDoctorId(e.target.value)} className="rounded-xl border p-3"><option value="">Médico responsável</option>{doctors.map(d=><option key={d.id} value={d.id}>{d.fullName}</option>)}</select></div><button className="mt-5 w-full rounded-xl bg-[#a3113a] p-3 font-bold text-white">Salvar paciente</button></form></div>}
 {form==="report"&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/45 p-4"><section className="mx-auto my-5 w-full max-w-3xl rounded-3xl bg-white p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Novo laudo</h2><p className="text-sm text-[#817578]">{patient?.name??"Selecione a paciente na tela de Laudos"}</p></div><button onClick={()=>setForm(null)}>×</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Modelo<select value={type} onChange={e=>setType(e.target.value as ReportType)} className="mt-2 w-full rounded-xl border p-3"><option value="prick_test">Laudo Prick</option><option value="patch_test">Laudo Patch</option></select></label>{type==="prick_test"?<div className="rounded-xl bg-[#f7f1ee] p-3 text-sm"><strong>Responsável técnico obrigatório:</strong><br/>Dr. Sergio Fabricio Maniglia</div>:<label className="text-sm font-bold">Responsável do Patch<select value={patchResponsible} onChange={e=>setPatchResponsible(e.target.value)} className="mt-2 w-full rounded-xl border p-3">{patchResponsibles.map(x=><option key={x}>{x}</option>)}</select></label>}</div><div className="mt-6 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Substância</th><th className="p-2">Resultado</th></tr></thead><tbody>{substances.map(x=><tr key={x} className="border-b"><td className="p-2">{x}</td><td className="p-2"><select value={results[x]??""} onChange={e=>setResults({...results,[x]:e.target.value})} className="rounded-lg border p-2"><option value="">Não informado</option><option value="-">Negativo (-)</option><option value="?">Duvidoso (?)</option><option value="+">Leve (+)</option><option value="++">Moderado (++)</option><option value="+++">Intenso (+++)</option></select></td></tr>)}</tbody></table></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Observações clínicas" className="mt-5 min-h-28 w-full rounded-xl border p-3"/><button disabled={!patient} onClick={()=>void saveReport()} className="mt-5 w-full rounded-xl bg-[#a3113a] p-3 font-bold text-white disabled:opacity-50">Salvar laudo</button></section></div>}
 </section></div></main>;
}
